### ISSUE TITLE
PM 4 Support?

### ISSUE THREAD

**Issue by shreyop200** [ClickedTran/MineralGUI#1]
Will be cool if you pursue to add this api support also for a new branch!

**Comment by ClickedTran** [comment]
I have 1 version of this plugin that supports api 4.0, if you want to download, I will update quickly to version 4.0
But instead of you can sell all at once, you have to go to each item to sell, do you need any more?

**Comment by shreyop200** [comment]
> I have 1 version of this plugin that supports api 4.0, if you want to download, I will update quickly to version 4.0 But instead of you can sell all at once, you have to go to each item to sell, do you need any more?

Thats also very cool, if you can provide it will still be cool

**Comment by ClickedTran** [comment]
> > I have 1 version of this plugin that supports api 4.0, if you want to download, I will update quickly to version 4.0 But instead of you can sell all at once, you have to go to each item to sell, do you need any more?
> 
> Thats also very cool, if you can provide it will still be cool

Since this is an old version, I made it into one file, it will have some long and confusing functions, sorry for the carelessness
Link download: https://github.com/Clickedtran/MineralGUI/releases/download/pm4/MineralGUI-PM4.zip
